servers:
  hosts:
    ansible-test-ynh:

      ansible_host: "51.15.100.225"

      # Needs to be "root" before post-install and "admin" w/ password (and sshpass) and "ansible_become_user: root" after.
      # Before post-install:
      # ansible_user: root

# After post-install:
      ansible_user: admin
      ansible_password: "{{ admin_password }}"
      ansible_become_user: root

        # Swap
      swap_file_size_mb: '2048'

      # Yunohost admin password
      ynh_admin_password: <admin_password>

      ynh_main_domain: ynh-demo.doxx.fr
      ynh_extra_domains: ~



      # If you don't want to use a noho.st url
      ynh_ignore_dyndns_server: False



      # The list of users.
      ynh_users:

        - name: janedoe
          pass: <janedoe_password>
          firstname: Jane
          lastname: Doe
          mail: jane.doe@ynh-demo.doxx.fr

        - name: bruno
          pass: <bruno_password>
          firstname: Bruno
          lastname: Bruno
          mail: bruno@ynh-demo.doxx.fr


      # admin user for apps
      user_app_admin: janedoe
      
      # The list of apps you want to install.
      ynh_apps:
        - label: Wiki # Label is important, it's a reference for the Playbook.
          link: dokuwiki # It can be the name of an official app or a github link
          args: # Provide here args. Path and domain are mandatory, other args depend of the app (cf manifest.json of app).
            path: '/wiki'
            domain: "{{ ynh_main_domain }}"
            admin: "{{ user_app_admin }}"
            is_public: 'yes'
            language: fr
        - label: Blog 
          link: wordpress 
          args:
            path: '/wordpress'
            domain: "{{ ynh_main_domain }}"
            admin: "{{ user_app_admin }}"
            language: fr_FR
            multisite: 'no'
            is_public: 'yes'
        # - label: Pad 
        #   link: etherpad_mypads 
        #   args:
        #     path: '/etherpad'
        #     domain: pad.ynh-demo.doxx.fr
        #     admin: "{{ user_app_admin }}"
        #     password: "{{ admin_password }}"
        #     language: fr
        #     is_public: 'yes'
        #     mypads: 'no'
        #     useldap: 'no'
        - label: Cloud 
          link: nextcloud
          args:
            path: '/nextcloud'
            domain: "{{ ynh_main_domain }}"
            admin: "{{ user_app_admin }}"
            # user_home: 'no' # Access the users home folder from Nextcloud?

  # TODO: Tricount-like (IHateMoney), Garradin, Discourse, Collabora, Mobilizon, Self-Hosting Security Dashboard, Dokuwiki, Borg, Mattermost, Nextcloud documents, Nextcloud agenda, Cockpit, OSSEC

